### ISSUE TITLE
Not working with latest connect version (1.x)

### ISSUE THREAD

**Issue by narf** [treygriffith/connect-mongodb#8] opened 2011-03-06 10:48 UTC
getting this error

```
Error: TypeError: Cannot set property data of #<Object> which has only a getter
    at Object.merge (/home/narf/as_tools/usr/local/lib/node/.npm/connect/1.0.3/package/lib/utils.js:55:14)
    at Object.Cookie (/home/narf/as_tools/usr/local/lib/node/.npm/connect/1.0.3/package/lib/middleware/session/cookie.js:26:22)
    at /home/narf/as_tools/usr/local/lib/node/.npm/connect/1.0.3/package/lib/middleware/session.js:316:23
    at /home/narf/as_tools/usr/local/lib/node/.npm/connect-mongodb/0.1.1/package/lib/connect-mongodb.js:133:9
    at [object Object].<anonymous> (/home/narf/as_tools/usr/local/lib/node/.npm/mongodb/0.9.1/package/lib/mongodb/collection.js:447:35)
    at [object Object].emit (events.js:45:17)
    at [object Object].<anonymous> (/home/narf/as_tools/usr/local/lib/node/.npm/mongodb/0.9.1/package/lib/mongodb/db.js:83:12)
    at [object Object].emit (events.js:42:17)
    at Socket.<anonymous> (/home/narf/as_tools/usr/local/lib/node/.npm/mongodb/0.9.1/package/lib/mongodb/connection.js:82:16)
    at Socket.emit (events.js:42:17)
```

**Comment by dvv** [comment] 2011-03-06 11:08
Users report the problem is solved if they put app.use(express.bodyParser()); before app.use(express.methodOverride());

**Comment by narf** [comment] 2011-03-06 12:27
This don't seem to work for me.

**Comment by acrognale** [comment] 2011-03-07 23:54
Putting (express.bodyParser()) before methodOverride isn't working for me either.

**Comment by schaermu** [comment] 2011-03-09 06:56
Definitely broken in latest connect release, shifting around middleware doesn't help for me either.

**Comment by Charuru** [comment] 2011-03-09 14:48
Need a fix here

**Comment by dvv** [comment] 2011-03-09 15:46
things will get clearer if one printed what options is merged at
https://github.com/senchalabs/connect/blob/master/lib/middleware/session/cookie.js#L25
(or circa, I just looked at the current connect master). Waiting for
feedback...

**Comment by wavded** [comment] 2011-03-09 19:32
Same issue, connect-redis seems to be up to speed with the latest connect api, if that helps.

**Comment by acrognale** [comment] 2011-03-09 21:34
Casey Banner has released a new library for using mongodb for a session store at https://github.com/kcbanner/connect-mongo. It's on NPM as well. Just use that for now I guess.

**Comment by dvv** [comment] 2011-03-10 06:13
Use it.

**Comment by jsteenkamp** [comment] 2011-03-13 21:09
kcbanner/connect-mongo works for me on connect@1.0.6 and express@2.0.0beta3

**Comment by masylum** [comment] 2011-03-13 23:55
Added reapInterval to remove expired sessions. Works with latest connect. closed by 6dffe5b03b76432bceacce349532bdbfd2a5e240 and closed by 6dffe5b03b76432bceacce349532bdbfd2a5e240

**Comment by jsteenkamp** [comment] 2011-03-14 01:18
Many thanks - works for me on connect@1.0.6.

**Closed as completed** 2011-03-14 06:55 UTC

**Comment by schaermu** [comment] 2011-03-17 07:21
Thanks alot for fixing!
