### ISSUE TITLE
Unexpected token ILLEGAL

### ISSUE THREAD

**Issue by paulshapiro** [treygriffith/connect-mongodb#9] opened 2011-03-21 04:01 UTC
Hi there,

I've upgrade to node 0.4.3 today, and with it lots of packages via npm. I made some minor code tweaks to make sure that Mongoose's models are defined properly, but that's about it.

Now, upon running the server and attempting a connection, I get this:

```
SyntaxError: Unexpected token ILLEGAL
at Object.parse (native)
at /usr/local/lib/node/.npm/connect-mongodb/0.2.1/package/lib/connect-mongodb.js:138:25
at [object Object].<anonymous> (/usr/local/lib/node/.npm/mongodb/0.9.1/package/lib/mongodb/collection.js:447:35)
at [object Object].emit (events.js:67:17)
at [object Object].<anonymous> (/usr/local/lib/node/.npm/mongodb/0.9.1/package/lib/mongodb/db.js:83:12)
at [object Object].emit (events.js:64:17)
at Socket.<anonymous> (/usr/local/lib/node/.npm/mongodb/0.9.1/package/lib/mongodb/connection.js:82:16)
at Socket.emit (events.js:64:17)
at Socket._onReadable (net.js:665:31)
at IOWatcher.onReadable [as callback] (net.js:177:10)
```

Also, if i just leave the server running, I'll eventually get this error:

```
 21 Mar 00:00:51 - [ERROR] TypeError

/usr/local/lib/node/.npm/connect-mongodb/0.2.1/package/lib/connect-mongodb.js:104
  _collection.remove({expires: {'$lte': Date.now()}}, function () { });
              ^
TypeError: Cannot call method 'remove' of null  
at Timer.<anonymous> (/usr/local/lib/node/.npm/connect-mongodb/0.2.1/package/lib/connect-mongodb.js:104:19)
at Timer.callback (timers.js:208:16)
```

Any idea what's up with this?

Thanks!  
Paul

**Comment by masylum** [comment] 2011-03-21 07:42
Can you paste here what do you have on mongodb? Maybe you still have sessions generated from the provious connect-mongodb which are not compatible with the current version.

The second one, I will take a look this afternoon if I have time. For now you can pass the option `reapInterval: -1`

**Comment by jeromegn** [comment] 2011-03-22 16:18
Had the same error. So I dropped the sessions collection and restarted my app. No cigar. Been wanting to upgrade for the `url` parameter. Downgraded back to 0.1.1. Works just fine now with the old parameters.

**Comment by masylum** [comment] 2011-03-22 22:17
Can you please provide a little bit more information? I can't reproduce any of the bugs :(

The module is so simple, should be easy to debug.

**Comment by paulshapiro** [comment] 2011-03-23 01:18
Sorry... I'd post the contents of my session collection but I dropped it too. I tried using reapInterval: -1, but the second issue seems to still occur occasionally. I have also gotten the first issue on launch even after wiping the collection. It seems very rare now, though.

Here's some module version info:
node 0.4.3
npm 0.3.16
mongodb (node driver) 0.9.1
connect-mongodb 0.2.1

My mongodb installation version (on dev at least, where this problem has been occurring) is 1.6.3. That could be part of the issue. I have a newer mongo installation on my prod server (1.8) but am not able to update node on the prod server to verify that it's a mongodb version issue (as it's the prod server).

Let me know if I can provide any additional specific info for ya.

Thanks for your work on this module.. :)

Paul

**Comment by masylum** [comment] 2011-03-23 18:47
removed unnecessary code. added throws on errors and JSON.parse bug closed by c0db91ad1d0cd3919636881e4d67ec836017e081

**Closed as completed by masylum** 2011-03-23 18:47 UTC
Labels: bug

**Comment by masylum** [comment] 2011-03-23 18:51
please `npm update connect-mongodb` and let me know if you still have this two issues. 

If you do, please open `/usr/local/lib/node/.npm/connect-mongodb/active/package/lib/connect-mongodb.js` with your editor and
- add `console.log(col);` to the line 93.
- add `console.log(data)` to the line 136.

Thank's in advance.

**Comment by paulshapiro** [comment] 2011-03-28 04:04
Since updating, I haven't encountered this issue throughout a day of testing. Thanks!!
